### ISSUE TITLE
Example of data?

### ISSUE THREAD

**Issue by Chunator** [lgajo/multiplexsage#1]
Hello, I'm trying to use your model and cite your paper. 
Can you provide a example of your data, or at least a description of the data input? 

Any description of data type & format, as well as description on how to run your model would be very time-saving.

Thank you in advance!

**Comment by lgajo** [comment]
Hi,

Yes, I will put them soon online!

The datasets are provided as networkx graph saved in json format.
I will soon add a description of how to run the model.

**Comment by lgajo** [comment]
Hi,
I have updated the README file, with all the information needed. Cheers :D
